### ISSUE TITLE
Should seasonal rating proposal updates be part of TROLIE?

### ISSUE THREAD

**Issue by getorymckeag** [trolie/spec#134]
As part of #5, the possibility of a separate clearinghouse for seasonal ratings is being discussed.  However, the ways that seasonal ratings get updated differ wildly across ISOs- TOs may access the LEP directly, OR may need to put seasonal ratings into the modeling process, OR LEP/TROLIE will sit behind existing ratings tools.  

So, GEV will definitely be building an API to allow users to submit ratings.  This is still a quite common use case, even if it is not a TO use case.  

By the way, to add to the wrinkles, GEV will need to support (for other customer requirements) submittal by "named" seasons.  I had thought to keep that out of TROLIE for now, but this would certainly make this issue more complex.

**Comment by catkins-miso** [comment]
I *think* your question is about a subtle semantic difference between "seasonal rating schedule" and "season rating proposal"? Out of an abundance of caution I'm going to restate some obvious things.

Creating/updating/sharing seasonal ratings schedules (SRS) is definitely an interop use case.

"Proposal" is ubiquitously used because it points to the fundamental transformation between a bunch of ratings (proposed limits) and a limit snapshot. Even with a single ratings provider, the possibility exists of an override by the RC/TP determining the limit.

The interop use cases for *reading* a proposal thus far are limited to a Ratings Provider monitoring their own submissions. The proposal inputs used to determine limits are available in detailed snapshots as "provenance".

Predefined Named seasons seems clearly a non-starter for interop, in the same way that predefined named emergency durations and requiring an explicit mrids are non-starters, yet the fundamental paradigm of "ratings proposal -> limits snapshot" works in RT, forecast, and--I am confident--seasonal. It works because the underlying information content is the same, we just make the implicit, explicit.

My suggestion is that we define the interop API and allow seasonal extents to be named in the SRS proposal but still require the start-end dates. Do the same thing on the SRS snapshot. If a vendor has a customer that insists on the mean of the string "FALL" in an API call, then I think I'd implement that via an adapter pattern in a new controller endpoint that internally translates using a configuration item for `FALL = <date range>`.

**Comment by catkins-miso** [comment]
Relatedly, I would like to update this image in the OpenAPI spec
![image](https://github.com/user-attachments/assets/6b34b65c-1ce6-4cf0-ab97-5c57f7abfce8)

**Comment by catkins-miso** [comment]
The answer was determined to be yes.
