### ISSUE TITLE
prebuild devcontainer

### ISSUE THREAD

**Issue by catkins-miso** [trolie/spec#18]
Not just a first-run perf optimization: MITM self-signed certs prevents some organizations from adopting.

See: https://containers.dev/guide/prebuild

This will probably be a new repo just for the devcontainer or follow this pattern: [`.github/.devcontainer`](https://github.com/craiglpeters/kubernetes-devcontainer/tree/master/.github/.devcontainer). We may ultimately need to solve the self-signed certs problem https://github.com/microsoft/vscode-remote-release/issues/6092 but I think if we just get the current dependencies into the devcontainer, we'll be fine.

**Comment by catkins-miso** [comment]
@getorymckeag please lmk if you can pull this image

`docker pull ghcr.io/trolie/spec-devcontainer:latest`

**Comment by caindy** [comment]
Rather than solve the enterprise self-signed certificate problem, I'm going to punt and assume that that folks using this repo can solve that problem on their own. At MISO we have a proxy for both npm and rubygems, so I will edit references to those and just ignore those when checking in. Concretely `.vscode/settings.json` will have
```json
"cmd": "npm_config_registry=... npx --yes @redocly/cli ..."
```
and both Gemfile and Gemfile.lock will have a custom `source`.

@getorymckeag lmk if that works for you too.
