### ISSUE TITLE
consider renaming temporary seasonal ratings to seasonal override

### ISSUE THREAD

**Issue by caindy** [trolie/spec#31]

**Comment by catkins-miso** [comment]
@getorymckeag Instead of
`temporary seasonal rating` ➡️ `temporary default static rating`
I propose
`temporary seasonal rating` ➡️ `seasonal override`

`Seasonal override` is a better name because it explicitly describes the effective (and intended) function of the rating in the operations horizons that TROLIE supports. In Operations an override is typically understood to prevail over another value for some period of time, even if that period of time is open ended. That's exactly the semantics of the API: A `period-start` is required but `period-end` is optional. Anecdotally, "seasonal override" is how I end up explaining what "temporary default static rating" means anyway.

**Comment by catkins-miso** [comment]
@getorymckeag I've asked @lreaves-spp to weigh in here. We had a good discussion on the original proposal of `temporary default static ratings`, but I'm hoping they'll agree that `seasonal override` is simple and gets the job done.

**Comment by lreaves-spp** [comment]
@getorymckeag and @catkins-miso, after discussing with others here, we agree "seasonal override" is a good rename.

**Comment by getorymckeag** [comment]
Agreed by steering committee 7/25
