### ISSUE TITLE
Determine verb, overall HTTP flow for submitting real-time proposals

### ISSUE THREAD

**Issue by getorymckeag** [trolie/spec#99]
Current spec has a POST, indicating a new proposal each time.  This is somewhat different from the forecast ratings PATCH paradigm.  Simply validate and agree on approach.  

Document Design decision.

**Comment by getorymckeag** [comment]
Notes from 4/11
- We stick with POST
- A POST is complete, meaning it represents the rating provider's entire obligation (cannot split along network model lines).

**Comment by caindy** [comment]
An important point in the rationale for not allowing partial RT proposals for a given Ratings Obligation is to ensure that all the proposed ratings are delivered atomically to the clearinghouse so that the Ratings Provider and Clearinghouse Provider are operating with consistent limits. For example, this goes a long way to preclude the possibility that in one Clearinghouse run some of the Ratings Provider's current RT ratings are used but not all: It is anticipated that a RT "ratings run" at the Ratings Provider will produce an atomic result that will be sent to the Clearinghouse Provider in fulfillment of the RT Ratings Obligation. Moreover, the need to split proposals in Forecasting is anticipated based on the size of some of the Rating Obligations, yet with RT ratings being only a single time period, even a large footprint will can be easily delivered in one request.

The primary trade-off to explore here is in not accepting a partial request.  With the Forecast Ratings Proposals, we consider the individual resource proposals in a Ratings Forecast Proposal for completeness; the overall Forecast Ratings Proposal may be accepted but the response will indicate that any of individual proposals in that submittal that do not have the full 240 hours are still outstanding obligations. In other words, the Ratings Provider is required to provide a complete forecast--all 240 hours--or it is not compliant, so acceptable, forecast.

Analogously, a RT Ratings Proposal that does not provide a complete snapshot of the state of the "ratings run" at the provider's EMS promotes inconsistency, if not out of compliance, so unprocessable. Therefore, any benefits that might be gained from allowing partial RT Ratings Proposals are effectively superfluous.

As a consequence of this decision, Ratings Providers should always impute a recourse rating where appropriate to ensure their Real-Time Ratings Proposals are complete vis-a-vis their Ratings Obligation.
